// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission06_mh2323.Models;

namespace mission06_mh2323.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230211061308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("mission06_mh2323.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Action/Comedy",
                            Director = "The Wachowskis",
                            Edited = false,
                            LentTo = "Becky",
                            Notes = "Trying to convince Becky Speed Racer is the best movie",
                            Rating = "PG",
                            Title = "Speed Racer",
                            Year = 2008
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Family/Musical",
                            Director = "Nathan Greno/Byron Howard",
                            Edited = false,
                            Rating = "PG",
                            Title = "Tangled",
                            Year = 2010
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Comedy/Fantasy",
                            Director = "Vicky Jenson/Andrew Adamson",
                            Edited = false,
                            Rating = "PG",
                            Title = "Shrek",
                            Year = 2001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
